server:
  port: 8085

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: create
  show-sql: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/hms
  username: postgres
  password: MiBu92

